version: "3.9"
services:
  nginx_static:
    build:
      context: server/frontend
      dockerfile: Dockerfile
    image: nginx_static
    ports:
      - 6900:80
    container_name: nginx_static
    links:
      - grpc_proxy
  grpc_proxy:
    build:
      context: server/grpc_proxy
      dockerfile: Dockerfile
    image: grpc_proxy
    container_name: grpc_proxy
    ports:
      - 6901:6901
      - 9901:9901
    links:
      - av_server
  av_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: av_server
    container_name: av_server
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
